apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>ArgoBox GitOps Demo</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 40px;
          background: #f5f8fa;
          color: #333;
          line-height: 1.6;
        }
        .container {
          max-width: 800px;
          margin: 0 auto;
          background: white;
          padding: 30px;
          border-radius: 8px;
          box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 {
          color: #2563eb;
          margin-top: 0;
        }
        .badge {
          display: inline-block;
          padding: 5px 10px;
          background: #4ade80;
          color: white;
          border-radius: 4px;
          font-size: 14px;
          margin-bottom: 20px;
        }
        .features {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 20px;
          margin: 30px 0;
        }
        .feature {
          background: #f1f5f9;
          padding: 20px;
          border-radius: 6px;
        }
        .feature h3 {
          margin-top: 0;
          color: #1e40af;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>ArgoBox GitOps Demo</h1>
        <div class="badge">Zero-Cost Local Development</div>
        
        <p>This page is being served from an NGINX container deployed automatically through Argo CD's GitOps process!</p>
        
        <div class="features">
          <div class="feature">
            <h3>GitOps Workflow</h3>
            <p>This application was deployed automatically when you pushed the manifests to your Git repository.</p>
          </div>
          <div class="feature">
            <h3>Zero AWS Costs</h3>
            <p>Running locally on Minikube instead of AWS EKS, saving $70-90/month in cloud costs.</p>
          </div>
          <div class="feature">
            <h3>Self-Healing</h3>
            <p>Any manual changes to this deployment will be automatically reverted to match Git.</p>
          </div>
          <div class="feature">
            <h3>Infrastructure as Code</h3>
            <p>All infrastructure and applications defined as code in a Git repository.</p>
          </div>
        </div>
        
        <p>Try making a change to this HTML in Git and watch it automatically update!</p>
      </div>
    </body>
    </html>
